global using Api.Helper;
global using Infrastructure;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.IdentityModel.Tokens;
global using Asp.Versioning;
global using System.Diagnostics;
global using System.Security.Cryptography;
